language: python
python:
- "3.5"
- "3.5-dev"

install:
- pip3 install -r requirements.txt
- pip3 install -e .
- pip install pytest-cov
- pip install codecov

script:
- pytest
- py.test --cov=./

after_success:
- codecov


