# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_app', '0004_auto_20170512_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_user_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
