# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_app', '0006_auto_20170515_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_demo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
